height: 320
keyframe:
- bbox_ratios:
  - -0.003
  - 0.011
  - 0.9908
  - 0.9999
  frame: 0
  global_frame: 203
  prompt: the grasshopper is walking
- bbox_ratios:
  - -0.0031
  - 0.0107
  - 0.9907
  - 0.9999
  frame: 1
  global_frame: 204
  prompt: the grasshopper is walking
- bbox_ratios:
  - -0.0031
  - 0.0105
  - 0.9906
  - 0.9999
  frame: 2
  global_frame: 205
  prompt: the grasshopper is walking
- bbox_ratios:
  - -0.0031
  - 0.0103
  - 0.9905
  - 0.9998
  frame: 3
  global_frame: 206
  prompt: the grasshopper is walking
- bbox_ratios:
  - -0.0031
  - 0.0101
  - 0.9905
  - 0.9998
  frame: 4
  global_frame: 207
  prompt: the grasshopper is walking
- bbox_ratios:
  - -0.0032
  - 0.0099
  - 0.9904
  - 0.9998
  frame: 5
  global_frame: 208
  prompt: the grasshopper is walking
- bbox_ratios:
  - -0.0032
  - 0.0096
  - 0.9903
  - 0.9997
  frame: 6
  global_frame: 209
  prompt: the grasshopper is walking
- bbox_ratios:
  - -0.0032
  - 0.0094
  - 0.9902
  - 0.9997
  frame: 7
  global_frame: 210
  prompt: the grasshopper is walking
- bbox_ratios:
  - -0.0032
  - 0.0092
  - 0.9902
  - 0.9997
  frame: 8
  global_frame: 211
  prompt: the grasshopper is walking
- bbox_ratios:
  - -0.0032
  - 0.009
  - 0.9901
  - 0.9996
  frame: 9
  global_frame: 212
  prompt: the grasshopper is walking
- bbox_ratios:
  - -0.0033
  - 0.0087
  - 0.99
  - 0.9996
  frame: 10
  global_frame: 213
  prompt: the grasshopper is walking
- bbox_ratios:
  - -0.0033
  - 0.0085
  - 0.99
  - 0.9996
  frame: 11
  global_frame: 214
  prompt: the grasshopper is walking
- bbox_ratios:
  - -0.0033
  - 0.0083
  - 0.9899
  - 0.9995
  frame: 12
  global_frame: 215
  prompt: the grasshopper is walking
- bbox_ratios:
  - -0.0033
  - 0.0081
  - 0.9898
  - 0.9995
  frame: 13
  global_frame: 216
  prompt: the grasshopper is walking
- bbox_ratios:
  - -0.0033
  - 0.0078
  - 0.9897
  - 0.9994
  frame: 14
  global_frame: 217
  prompt: the grasshopper is walking
- bbox_ratios:
  - -0.0009
  - 0.006
  - 0.9918
  - 0.9974
  frame: 15
  global_frame: 218
  prompt: the grasshopper is walking
- bbox_ratios:
  - 0.0015
  - 0.0042
  - 0.9938
  - 0.9954
  frame: 16
  global_frame: 219
  prompt: the grasshopper is walking
- bbox_ratios:
  - 0.0039
  - 0.0024
  - 0.9958
  - 0.9934
  frame: 17
  global_frame: 220
  prompt: the grasshopper is walking
- bbox_ratios:
  - 0.0063
  - 0.0006
  - 0.9979
  - 0.9914
  frame: 18
  global_frame: 221
  prompt: the grasshopper is walking
- bbox_ratios:
  - 0.0121
  - 0.0028
  - 0.9972
  - 0.9921
  frame: 19
  global_frame: 222
  prompt: the grasshopper is walking
- bbox_ratios:
  - 0.0178
  - 0.005
  - 0.9965
  - 0.9928
  frame: 20
  global_frame: 223
  prompt: the grasshopper is walking
- bbox_ratios:
  - 0.0236
  - 0.0071
  - 0.9958
  - 0.9936
  frame: 21
  global_frame: 224
  prompt: the grasshopper is walking
- bbox_ratios:
  - 0.0293
  - 0.0093
  - 0.9951
  - 0.9943
  frame: 22
  global_frame: 225
  prompt: the grasshopper is walking
- bbox_ratios:
  - 0.0351
  - 0.0115
  - 0.9944
  - 0.9951
  frame: 23
  global_frame: 226
  prompt: the grasshopper is walking
motion_id: 32
motion_iter: 0
num_inference_steps: null
object_name: grasshopper
seed: 4
source_clip: CCYVLEQQ_136_252
token_inds:
- 2
trailblazer:
  num_dd_spatial_steps: 5
  num_dd_temporal_steps: 5
  spatial_strengthen_scale: 0.15
  spatial_weaken_scale: 0.001
  temp_strengthen_scale: 0.15
  temp_weaken_scale: 0.001
  trailing_length: 15
width: 320
