height: 320
keyframe:
- bbox_ratios:
  - 0.2195
  - 0.4762
  - 0.639
  - 0.9988
  frame: 0
  global_frame: 265
  prompt: the mosquito larva is moving
- bbox_ratios:
  - 0.2278
  - 0.4539
  - 0.6443
  - 0.998
  frame: 1
  global_frame: 266
  prompt: the mosquito larva is moving
- bbox_ratios:
  - 0.236
  - 0.4315
  - 0.6496
  - 0.9972
  frame: 2
  global_frame: 267
  prompt: the mosquito larva is moving
- bbox_ratios:
  - 0.207
  - 0.3737
  - 0.6278
  - 0.9857
  frame: 3
  global_frame: 268
  prompt: the mosquito larva is moving
- bbox_ratios:
  - 0.1781
  - 0.3158
  - 0.606
  - 0.9742
  frame: 4
  global_frame: 269
  prompt: the mosquito larva is moving
- bbox_ratios:
  - 0.1491
  - 0.258
  - 0.5842
  - 0.9628
  frame: 5
  global_frame: 270
  prompt: the mosquito larva is moving
- bbox_ratios:
  - 0.1202
  - 0.2001
  - 0.5625
  - 0.9513
  frame: 6
  global_frame: 271
  prompt: the mosquito larva is moving
- bbox_ratios:
  - 0.0912
  - 0.1423
  - 0.5407
  - 0.9398
  frame: 7
  global_frame: 272
  prompt: the mosquito larva is moving
- bbox_ratios:
  - 0.0623
  - 0.0844
  - 0.5189
  - 0.9283
  frame: 8
  global_frame: 273
  prompt: the mosquito larva is moving
- bbox_ratios:
  - 0.0506
  - 0.0713
  - 0.5851
  - 0.9637
  frame: 9
  global_frame: 274
  prompt: the mosquito larva is moving
- bbox_ratios:
  - 0.0504
  - 0.0673
  - 0.5857
  - 0.9655
  frame: 10
  global_frame: 275
  prompt: the mosquito larva is moving
- bbox_ratios:
  - 0.0501
  - 0.0633
  - 0.5864
  - 0.9673
  frame: 11
  global_frame: 276
  prompt: the mosquito larva is moving
- bbox_ratios:
  - 0.0499
  - 0.0592
  - 0.587
  - 0.9692
  frame: 12
  global_frame: 277
  prompt: the mosquito larva is moving
- bbox_ratios:
  - 0.0497
  - 0.0552
  - 0.5876
  - 0.971
  frame: 13
  global_frame: 278
  prompt: the mosquito larva is moving
- bbox_ratios:
  - 0.0495
  - 0.0511
  - 0.5883
  - 0.9728
  frame: 14
  global_frame: 279
  prompt: the mosquito larva is moving
- bbox_ratios:
  - 0.0492
  - 0.0471
  - 0.5889
  - 0.9747
  frame: 15
  global_frame: 280
  prompt: the mosquito larva is moving
- bbox_ratios:
  - 0.049
  - 0.0431
  - 0.5895
  - 0.9765
  frame: 16
  global_frame: 281
  prompt: the mosquito larva is moving
- bbox_ratios:
  - 0.0488
  - 0.039
  - 0.5902
  - 0.9783
  frame: 17
  global_frame: 282
  prompt: the mosquito larva is moving
- bbox_ratios:
  - 0.0486
  - 0.035
  - 0.5908
  - 0.9802
  frame: 18
  global_frame: 283
  prompt: the mosquito larva is moving
- bbox_ratios:
  - 0.0484
  - 0.031
  - 0.5914
  - 0.982
  frame: 19
  global_frame: 284
  prompt: the mosquito larva is moving
- bbox_ratios:
  - 0.0481
  - 0.0269
  - 0.5921
  - 0.9838
  frame: 20
  global_frame: 285
  prompt: the mosquito larva is moving
- bbox_ratios:
  - 0.0479
  - 0.0229
  - 0.5927
  - 0.9857
  frame: 21
  global_frame: 286
  prompt: the mosquito larva is moving
- bbox_ratios:
  - 0.0477
  - 0.0189
  - 0.5933
  - 0.9875
  frame: 22
  global_frame: 287
  prompt: the mosquito larva is moving
- bbox_ratios:
  - 0.0475
  - 0.0148
  - 0.594
  - 0.9893
  frame: 23
  global_frame: 288
  prompt: the mosquito larva is moving
motion_id: 13
motion_iter: 2
num_inference_steps: null
object_name: larva
seed: 4
source_clip: AFIXMLZD_199_362
token_inds:
- 3
trailblazer:
  num_dd_spatial_steps: 5
  num_dd_temporal_steps: 5
  spatial_strengthen_scale: 0.15
  spatial_weaken_scale: 0.001
  temp_strengthen_scale: 0.15
  temp_weaken_scale: 0.001
  trailing_length: 15
width: 320
