height: 320
keyframe:
- bbox_ratios:
  - 0.2451
  - 0.5517
  - 0.6968
  - 0.8826
  frame: 0
  global_frame: 1071
  prompt: the leech is moving
- bbox_ratios:
  - 0.2491
  - 0.5273
  - 0.697
  - 0.862
  frame: 1
  global_frame: 1072
  prompt: the leech is moving
- bbox_ratios:
  - 0.2531
  - 0.5029
  - 0.6971
  - 0.8414
  frame: 2
  global_frame: 1073
  prompt: the leech is moving
- bbox_ratios:
  - 0.2571
  - 0.4785
  - 0.6973
  - 0.8208
  frame: 3
  global_frame: 1074
  prompt: the leech is moving
- bbox_ratios:
  - 0.261
  - 0.4541
  - 0.6974
  - 0.8002
  frame: 4
  global_frame: 1075
  prompt: the leech is moving
- bbox_ratios:
  - 0.265
  - 0.4297
  - 0.6975
  - 0.7796
  frame: 5
  global_frame: 1076
  prompt: the leech is moving
- bbox_ratios:
  - 0.269
  - 0.4053
  - 0.6977
  - 0.759
  frame: 6
  global_frame: 1077
  prompt: the leech is moving
- bbox_ratios:
  - 0.2729
  - 0.3809
  - 0.6978
  - 0.7384
  frame: 7
  global_frame: 1078
  prompt: the leech is moving
- bbox_ratios:
  - 0.2769
  - 0.3565
  - 0.6979
  - 0.7178
  frame: 8
  global_frame: 1079
  prompt: the leech is moving
- bbox_ratios:
  - 0.2809
  - 0.3321
  - 0.6981
  - 0.6972
  frame: 9
  global_frame: 1080
  prompt: the leech is moving
- bbox_ratios:
  - 0.2849
  - 0.3077
  - 0.6982
  - 0.6767
  frame: 10
  global_frame: 1081
  prompt: the leech is moving
- bbox_ratios:
  - 0.2888
  - 0.2833
  - 0.6984
  - 0.6561
  frame: 11
  global_frame: 1082
  prompt: the leech is moving
- bbox_ratios:
  - 0.2928
  - 0.2589
  - 0.6985
  - 0.6355
  frame: 12
  global_frame: 1083
  prompt: the leech is moving
- bbox_ratios:
  - 0.2968
  - 0.2345
  - 0.6986
  - 0.6149
  frame: 13
  global_frame: 1084
  prompt: the leech is moving
- bbox_ratios:
  - 0.3008
  - 0.2101
  - 0.6988
  - 0.5943
  frame: 14
  global_frame: 1085
  prompt: the leech is moving
- bbox_ratios:
  - 0.3008
  - 0.2081
  - 0.69
  - 0.5895
  frame: 15
  global_frame: 1086
  prompt: the leech is moving
- bbox_ratios:
  - 0.3008
  - 0.206
  - 0.6812
  - 0.5848
  frame: 16
  global_frame: 1087
  prompt: the leech is moving
- bbox_ratios:
  - 0.3009
  - 0.204
  - 0.6724
  - 0.58
  frame: 17
  global_frame: 1088
  prompt: the leech is moving
- bbox_ratios:
  - 0.3009
  - 0.202
  - 0.6637
  - 0.5752
  frame: 18
  global_frame: 1089
  prompt: the leech is moving
- bbox_ratios:
  - 0.301
  - 0.2
  - 0.6549
  - 0.5705
  frame: 19
  global_frame: 1090
  prompt: the leech is moving
- bbox_ratios:
  - 0.301
  - 0.198
  - 0.6461
  - 0.5657
  frame: 20
  global_frame: 1091
  prompt: the leech is moving
- bbox_ratios:
  - 0.301
  - 0.1959
  - 0.6373
  - 0.5609
  frame: 21
  global_frame: 1092
  prompt: the leech is moving
- bbox_ratios:
  - 0.3011
  - 0.1939
  - 0.6286
  - 0.5562
  frame: 22
  global_frame: 1093
  prompt: the leech is moving
- bbox_ratios:
  - 0.3011
  - 0.1919
  - 0.6198
  - 0.5514
  frame: 23
  global_frame: 1094
  prompt: the leech is moving
motion_id: 1
motion_iter: 1
num_inference_steps: null
object_name: leech
seed: 4
source_clip: ERXBFUNV_991_1173
token_inds:
- 2
trailblazer:
  num_dd_spatial_steps: 5
  num_dd_temporal_steps: 5
  spatial_strengthen_scale: 0.15
  spatial_weaken_scale: 0.001
  temp_strengthen_scale: 0.15
  temp_weaken_scale: 0.001
  trailing_length: 15
width: 320
