height: 320
keyframe:
- bbox_ratios:
  - 0.11
  - 0.0056
  - 0.8438
  - 1.0003
  frame: 0
  global_frame: 1121
  prompt: the grey langur is exploring
- bbox_ratios:
  - 0.1113
  - 0.0058
  - 0.8441
  - 1.0009
  frame: 1
  global_frame: 1122
  prompt: the grey langur is exploring
- bbox_ratios:
  - 0.1127
  - 0.0061
  - 0.8444
  - 1.0015
  frame: 2
  global_frame: 1123
  prompt: the grey langur is exploring
- bbox_ratios:
  - 0.114
  - 0.0063
  - 0.8448
  - 1.002
  frame: 3
  global_frame: 1124
  prompt: the grey langur is exploring
- bbox_ratios:
  - 0.1138
  - 0.0042
  - 0.8471
  - 0.9999
  frame: 4
  global_frame: 1125
  prompt: the grey langur is exploring
- bbox_ratios:
  - 0.1135
  - 0.002
  - 0.8494
  - 0.9979
  frame: 5
  global_frame: 1126
  prompt: the grey langur is exploring
- bbox_ratios:
  - 0.1133
  - -0.0001
  - 0.8517
  - 0.9958
  frame: 6
  global_frame: 1127
  prompt: the grey langur is exploring
- bbox_ratios:
  - 0.114
  - 0.0002
  - 0.8512
  - 0.9962
  frame: 7
  global_frame: 1128
  prompt: the grey langur is exploring
- bbox_ratios:
  - 0.1147
  - 0.0005
  - 0.8506
  - 0.9966
  frame: 8
  global_frame: 1129
  prompt: the grey langur is exploring
- bbox_ratios:
  - 0.1154
  - 0.0008
  - 0.85
  - 0.997
  frame: 9
  global_frame: 1130
  prompt: the grey langur is exploring
- bbox_ratios:
  - 0.1161
  - 0.0011
  - 0.8494
  - 0.9974
  frame: 10
  global_frame: 1131
  prompt: the grey langur is exploring
- bbox_ratios:
  - 0.1169
  - 0.0013
  - 0.8488
  - 0.9978
  frame: 11
  global_frame: 1132
  prompt: the grey langur is exploring
- bbox_ratios:
  - 0.1176
  - 0.0016
  - 0.8482
  - 0.9982
  frame: 12
  global_frame: 1133
  prompt: the grey langur is exploring
- bbox_ratios:
  - 0.1183
  - 0.0019
  - 0.8476
  - 0.9986
  frame: 13
  global_frame: 1134
  prompt: the grey langur is exploring
- bbox_ratios:
  - 0.119
  - 0.0022
  - 0.847
  - 0.999
  frame: 14
  global_frame: 1135
  prompt: the grey langur is exploring
- bbox_ratios:
  - 0.1197
  - 0.0025
  - 0.8464
  - 0.9994
  frame: 15
  global_frame: 1136
  prompt: the grey langur is exploring
- bbox_ratios:
  - 0.1204
  - 0.0028
  - 0.8458
  - 0.9998
  frame: 16
  global_frame: 1137
  prompt: the grey langur is exploring
- bbox_ratios:
  - 0.1204
  - 0.0028
  - 0.846
  - 0.9999
  frame: 17
  global_frame: 1138
  prompt: the grey langur is exploring
- bbox_ratios:
  - 0.118
  - 0.0035
  - 0.8495
  - 0.9997
  frame: 18
  global_frame: 1139
  prompt: the grey langur is exploring
- bbox_ratios:
  - 0.1185
  - 0.0031
  - 0.8502
  - 0.9995
  frame: 19
  global_frame: 1140
  prompt: the grey langur is exploring
- bbox_ratios:
  - 0.1171
  - 0.0031
  - 0.8547
  - 0.9992
  frame: 20
  global_frame: 1141
  prompt: the grey langur is exploring
- bbox_ratios:
  - 0.1189
  - 0.0049
  - 0.8523
  - 1.001
  frame: 21
  global_frame: 1142
  prompt: the grey langur is exploring
- bbox_ratios:
  - 0.118
  - 0.0044
  - 0.852
  - 1.0003
  frame: 22
  global_frame: 1143
  prompt: the grey langur is exploring
- bbox_ratios:
  - 0.1177
  - 0.0045
  - 0.8513
  - 1.0004
  frame: 23
  global_frame: 1144
  prompt: the grey langur is exploring
motion_id: 17
motion_iter: 0
num_inference_steps: null
object_name: langur
seed: 4
source_clip: AGJEQNPL_1104_1166
token_inds:
- 3
trailblazer:
  num_dd_spatial_steps: 5
  num_dd_temporal_steps: 5
  spatial_strengthen_scale: 0.15
  spatial_weaken_scale: 0.001
  temp_strengthen_scale: 0.15
  temp_weaken_scale: 0.001
  trailing_length: 15
width: 320
