height: 320
keyframe:
- bbox_ratios:
  - 0.4006
  - 0.6908
  - 0.6939
  - 0.8261
  frame: 0
  global_frame: 1374
  prompt: the racoon is walking
- bbox_ratios:
  - 0.3991
  - 0.6906
  - 0.6938
  - 0.8259
  frame: 1
  global_frame: 1375
  prompt: the racoon is walking
- bbox_ratios:
  - 0.401
  - 0.691
  - 0.6938
  - 0.8258
  frame: 2
  global_frame: 1376
  prompt: the racoon is walking
- bbox_ratios:
  - 0.4016
  - 0.6899
  - 0.6936
  - 0.827
  frame: 3
  global_frame: 1377
  prompt: the racoon is walking
- bbox_ratios:
  - 0.4001
  - 0.6896
  - 0.6938
  - 0.8266
  frame: 4
  global_frame: 1378
  prompt: the racoon is walking
- bbox_ratios:
  - 0.3997
  - 0.6895
  - 0.6938
  - 0.8266
  frame: 5
  global_frame: 1379
  prompt: the racoon is walking
- bbox_ratios:
  - 0.3994
  - 0.6896
  - 0.6938
  - 0.8265
  frame: 6
  global_frame: 1380
  prompt: the racoon is walking
- bbox_ratios:
  - 0.4002
  - 0.6897
  - 0.6937
  - 0.8265
  frame: 7
  global_frame: 1381
  prompt: the racoon is walking
- bbox_ratios:
  - 0.4015
  - 0.6903
  - 0.6934
  - 0.8266
  frame: 8
  global_frame: 1382
  prompt: the racoon is walking
- bbox_ratios:
  - 0.4012
  - 0.6903
  - 0.6935
  - 0.8266
  frame: 9
  global_frame: 1383
  prompt: the racoon is walking
- bbox_ratios:
  - 0.4006
  - 0.6903
  - 0.6935
  - 0.8267
  frame: 10
  global_frame: 1384
  prompt: the racoon is walking
- bbox_ratios:
  - 0.4008
  - 0.6902
  - 0.6937
  - 0.8267
  frame: 11
  global_frame: 1385
  prompt: the racoon is walking
- bbox_ratios:
  - 0.4013
  - 0.6904
  - 0.6937
  - 0.8266
  frame: 12
  global_frame: 1386
  prompt: the racoon is walking
- bbox_ratios:
  - 0.4011
  - 0.6903
  - 0.6937
  - 0.8266
  frame: 13
  global_frame: 1387
  prompt: the racoon is walking
- bbox_ratios:
  - 0.4009
  - 0.6901
  - 0.6937
  - 0.8266
  frame: 14
  global_frame: 1388
  prompt: the racoon is walking
- bbox_ratios:
  - 0.401
  - 0.6902
  - 0.6936
  - 0.8267
  frame: 15
  global_frame: 1389
  prompt: the racoon is walking
- bbox_ratios:
  - 0.4007
  - 0.6901
  - 0.6937
  - 0.8268
  frame: 16
  global_frame: 1390
  prompt: the racoon is walking
- bbox_ratios:
  - 0.4006
  - 0.6902
  - 0.6937
  - 0.8267
  frame: 17
  global_frame: 1391
  prompt: the racoon is walking
- bbox_ratios:
  - 0.4009
  - 0.6897
  - 0.694
  - 0.8271
  frame: 18
  global_frame: 1392
  prompt: the racoon is walking
- bbox_ratios:
  - 0.4012
  - 0.6899
  - 0.694
  - 0.8272
  frame: 19
  global_frame: 1393
  prompt: the racoon is walking
- bbox_ratios:
  - 0.4013
  - 0.6897
  - 0.6941
  - 0.8271
  frame: 20
  global_frame: 1394
  prompt: the racoon is walking
- bbox_ratios:
  - 0.4012
  - 0.6897
  - 0.6941
  - 0.8271
  frame: 21
  global_frame: 1395
  prompt: the racoon is walking
- bbox_ratios:
  - 0.401
  - 0.6898
  - 0.6941
  - 0.8273
  frame: 22
  global_frame: 1396
  prompt: the racoon is walking
- bbox_ratios:
  - 0.3966
  - 0.6908
  - 0.6951
  - 0.8331
  frame: 23
  global_frame: 1397
  prompt: the racoon is walking
motion_id: 27
motion_iter: 2
num_inference_steps: null
object_name: racoon
seed: 4
source_clip: JHXMURAC_1308_1404
token_inds:
- 2
trailblazer:
  num_dd_spatial_steps: 5
  num_dd_temporal_steps: 5
  spatial_strengthen_scale: 0.15
  spatial_weaken_scale: 0.001
  temp_strengthen_scale: 0.15
  temp_weaken_scale: 0.001
  trailing_length: 15
width: 320
