height: 320
keyframe:
- bbox_ratios:
  - 0.0334
  - 0.0013
  - 0.3413
  - 0.188
  frame: 0
  global_frame: 564
  prompt: the dolphin is swimming
- bbox_ratios:
  - 0.0376
  - 0.0022
  - 0.3443
  - 0.1886
  frame: 1
  global_frame: 565
  prompt: the dolphin is swimming
- bbox_ratios:
  - 0.0419
  - 0.003
  - 0.3474
  - 0.1893
  frame: 2
  global_frame: 566
  prompt: the dolphin is swimming
- bbox_ratios:
  - 0.0462
  - 0.0039
  - 0.3505
  - 0.19
  frame: 3
  global_frame: 567
  prompt: the dolphin is swimming
- bbox_ratios:
  - 0.0504
  - 0.0047
  - 0.3535
  - 0.1906
  frame: 4
  global_frame: 568
  prompt: the dolphin is swimming
- bbox_ratios:
  - 0.0547
  - 0.0056
  - 0.3566
  - 0.1913
  frame: 5
  global_frame: 569
  prompt: the dolphin is swimming
- bbox_ratios:
  - 0.059
  - 0.0064
  - 0.3597
  - 0.192
  frame: 6
  global_frame: 570
  prompt: the dolphin is swimming
- bbox_ratios:
  - 0.0632
  - 0.0073
  - 0.3627
  - 0.1927
  frame: 7
  global_frame: 571
  prompt: the dolphin is swimming
- bbox_ratios:
  - 0.0675
  - 0.0082
  - 0.3658
  - 0.1933
  frame: 8
  global_frame: 572
  prompt: the dolphin is swimming
- bbox_ratios:
  - 0.0718
  - 0.009
  - 0.3689
  - 0.194
  frame: 9
  global_frame: 573
  prompt: the dolphin is swimming
- bbox_ratios:
  - 0.076
  - 0.0099
  - 0.3719
  - 0.1947
  frame: 10
  global_frame: 574
  prompt: the dolphin is swimming
- bbox_ratios:
  - 0.0803
  - 0.0107
  - 0.375
  - 0.1954
  frame: 11
  global_frame: 575
  prompt: the dolphin is swimming
- bbox_ratios:
  - 0.0846
  - 0.0116
  - 0.3781
  - 0.196
  frame: 12
  global_frame: 576
  prompt: the dolphin is swimming
- bbox_ratios:
  - 0.0888
  - 0.0124
  - 0.3811
  - 0.1967
  frame: 13
  global_frame: 577
  prompt: the dolphin is swimming
- bbox_ratios:
  - 0.0931
  - 0.0133
  - 0.3842
  - 0.1974
  frame: 14
  global_frame: 578
  prompt: the dolphin is swimming
- bbox_ratios:
  - 0.0974
  - 0.0141
  - 0.3872
  - 0.198
  frame: 15
  global_frame: 579
  prompt: the dolphin is swimming
- bbox_ratios:
  - 0.1016
  - 0.015
  - 0.3903
  - 0.1987
  frame: 16
  global_frame: 580
  prompt: the dolphin is swimming
- bbox_ratios:
  - 0.1059
  - 0.0158
  - 0.3934
  - 0.1994
  frame: 17
  global_frame: 581
  prompt: the dolphin is swimming
- bbox_ratios:
  - 0.1102
  - 0.0167
  - 0.3964
  - 0.2001
  frame: 18
  global_frame: 582
  prompt: the dolphin is swimming
- bbox_ratios:
  - 0.1144
  - 0.0175
  - 0.3995
  - 0.2007
  frame: 19
  global_frame: 583
  prompt: the dolphin is swimming
- bbox_ratios:
  - 0.1187
  - 0.0184
  - 0.4026
  - 0.2014
  frame: 20
  global_frame: 584
  prompt: the dolphin is swimming
- bbox_ratios:
  - 0.123
  - 0.0192
  - 0.4056
  - 0.2021
  frame: 21
  global_frame: 585
  prompt: the dolphin is swimming
- bbox_ratios:
  - 0.1272
  - 0.0201
  - 0.4087
  - 0.2028
  frame: 22
  global_frame: 586
  prompt: the dolphin is swimming
- bbox_ratios:
  - 0.1315
  - 0.0209
  - 0.4118
  - 0.2034
  frame: 23
  global_frame: 587
  prompt: the dolphin is swimming
motion_id: 6
motion_iter: 2
num_inference_steps: null
object_name: dolphin
seed: 4
source_clip: AHYRBFGA_537_708
token_inds:
- 2
trailblazer:
  num_dd_spatial_steps: 5
  num_dd_temporal_steps: 5
  spatial_strengthen_scale: 0.15
  spatial_weaken_scale: 0.001
  temp_strengthen_scale: 0.15
  temp_weaken_scale: 0.001
  trailing_length: 15
width: 320
