height: 320
keyframe:
- bbox_ratios:
  - 0.1857
  - 0.3706
  - 1.0048
  - 0.7624
  frame: 0
  global_frame: 531
  prompt: the stingray is swimming
- bbox_ratios:
  - 0.1801
  - 0.3626
  - 1.0021
  - 0.7619
  frame: 1
  global_frame: 532
  prompt: the stingray is swimming
- bbox_ratios:
  - 0.1773
  - 0.3688
  - 1.0106
  - 0.7577
  frame: 2
  global_frame: 533
  prompt: the stingray is swimming
- bbox_ratios:
  - 0.1689
  - 0.3886
  - 0.9979
  - 0.76
  frame: 3
  global_frame: 534
  prompt: the stingray is swimming
- bbox_ratios:
  - 0.171
  - 0.3736
  - 0.9986
  - 0.7599
  frame: 4
  global_frame: 535
  prompt: the stingray is swimming
- bbox_ratios:
  - 0.1656
  - 0.3597
  - 1.0036
  - 0.7545
  frame: 5
  global_frame: 536
  prompt: the stingray is swimming
- bbox_ratios:
  - 0.172
  - 0.3592
  - 0.9994
  - 0.7541
  frame: 6
  global_frame: 537
  prompt: the stingray is swimming
- bbox_ratios:
  - 0.1691
  - 0.3486
  - 0.9992
  - 0.7508
  frame: 7
  global_frame: 538
  prompt: the stingray is swimming
- bbox_ratios:
  - 0.1637
  - 0.3447
  - 0.9924
  - 0.7509
  frame: 8
  global_frame: 539
  prompt: the stingray is swimming
- bbox_ratios:
  - 0.1674
  - 0.3397
  - 0.9881
  - 0.747
  frame: 9
  global_frame: 540
  prompt: the stingray is swimming
- bbox_ratios:
  - 0.1581
  - 0.342
  - 0.9842
  - 0.7484
  frame: 10
  global_frame: 541
  prompt: the stingray is swimming
- bbox_ratios:
  - 0.1539
  - 0.3248
  - 0.9836
  - 0.7462
  frame: 11
  global_frame: 542
  prompt: the stingray is swimming
- bbox_ratios:
  - 0.1564
  - 0.3249
  - 0.9868
  - 0.7466
  frame: 12
  global_frame: 543
  prompt: the stingray is swimming
- bbox_ratios:
  - 0.1625
  - 0.3196
  - 0.9868
  - 0.7449
  frame: 13
  global_frame: 544
  prompt: the stingray is swimming
- bbox_ratios:
  - 0.163
  - 0.3154
  - 0.9773
  - 0.7417
  frame: 14
  global_frame: 545
  prompt: the stingray is swimming
- bbox_ratios:
  - 0.1597
  - 0.312
  - 0.9752
  - 0.7422
  frame: 15
  global_frame: 546
  prompt: the stingray is swimming
- bbox_ratios:
  - 0.1624
  - 0.3047
  - 0.9737
  - 0.7402
  frame: 16
  global_frame: 547
  prompt: the stingray is swimming
- bbox_ratios:
  - 0.1546
  - 0.3116
  - 0.9658
  - 0.739
  frame: 17
  global_frame: 548
  prompt: the stingray is swimming
- bbox_ratios:
  - 0.1545
  - 0.3122
  - 0.9659
  - 0.7393
  frame: 18
  global_frame: 549
  prompt: the stingray is swimming
- bbox_ratios:
  - 0.1588
  - 0.2987
  - 0.9655
  - 0.7328
  frame: 19
  global_frame: 550
  prompt: the stingray is swimming
- bbox_ratios:
  - 0.1647
  - 0.3022
  - 0.9651
  - 0.7302
  frame: 20
  global_frame: 551
  prompt: the stingray is swimming
- bbox_ratios:
  - 0.1597
  - 0.3109
  - 0.9609
  - 0.7308
  frame: 21
  global_frame: 552
  prompt: the stingray is swimming
- bbox_ratios:
  - 0.1604
  - 0.3135
  - 0.9528
  - 0.7287
  frame: 22
  global_frame: 553
  prompt: the stingray is swimming
- bbox_ratios:
  - 0.1606
  - 0.3137
  - 0.9518
  - 0.7257
  frame: 23
  global_frame: 554
  prompt: the stingray is swimming
motion_id: 16
motion_iter: 2
num_inference_steps: null
object_name: stingray
seed: 4
source_clip: HDYVCDWZ_412_624
token_inds:
- 2
trailblazer:
  num_dd_spatial_steps: 5
  num_dd_temporal_steps: 5
  spatial_strengthen_scale: 0.15
  spatial_weaken_scale: 0.001
  temp_strengthen_scale: 0.15
  temp_weaken_scale: 0.001
  trailing_length: 15
width: 320
