height: 320
keyframe:
- bbox_ratios:
  - 0.4255
  - 0.3971
  - 0.535
  - 0.4817
  frame: 0
  global_frame: 1727
  prompt: the caribou is walking
- bbox_ratios:
  - 0.415
  - 0.3985
  - 0.5353
  - 0.4909
  frame: 1
  global_frame: 1728
  prompt: the caribou is walking
- bbox_ratios:
  - 0.4044
  - 0.4
  - 0.5357
  - 0.5002
  frame: 2
  global_frame: 1729
  prompt: the caribou is walking
- bbox_ratios:
  - 0.3939
  - 0.4014
  - 0.5361
  - 0.5094
  frame: 3
  global_frame: 1730
  prompt: the caribou is walking
- bbox_ratios:
  - 0.3833
  - 0.4028
  - 0.5364
  - 0.5187
  frame: 4
  global_frame: 1731
  prompt: the caribou is walking
- bbox_ratios:
  - 0.3728
  - 0.4043
  - 0.5368
  - 0.5279
  frame: 5
  global_frame: 1732
  prompt: the caribou is walking
- bbox_ratios:
  - 0.3622
  - 0.4057
  - 0.5371
  - 0.5372
  frame: 6
  global_frame: 1733
  prompt: the caribou is walking
- bbox_ratios:
  - 0.3517
  - 0.4072
  - 0.5375
  - 0.5464
  frame: 7
  global_frame: 1734
  prompt: the caribou is walking
- bbox_ratios:
  - 0.3411
  - 0.4086
  - 0.5378
  - 0.5557
  frame: 8
  global_frame: 1735
  prompt: the caribou is walking
- bbox_ratios:
  - 0.3306
  - 0.41
  - 0.5382
  - 0.5649
  frame: 9
  global_frame: 1736
  prompt: the caribou is walking
- bbox_ratios:
  - 0.32
  - 0.4115
  - 0.5385
  - 0.5742
  frame: 10
  global_frame: 1737
  prompt: the caribou is walking
- bbox_ratios:
  - 0.3095
  - 0.4129
  - 0.5389
  - 0.5834
  frame: 11
  global_frame: 1738
  prompt: the caribou is walking
- bbox_ratios:
  - 0.2989
  - 0.4144
  - 0.5392
  - 0.5926
  frame: 12
  global_frame: 1739
  prompt: the caribou is walking
- bbox_ratios:
  - 0.2884
  - 0.4158
  - 0.5396
  - 0.6019
  frame: 13
  global_frame: 1740
  prompt: the caribou is walking
- bbox_ratios:
  - 0.2778
  - 0.4172
  - 0.54
  - 0.6111
  frame: 14
  global_frame: 1741
  prompt: the caribou is walking
- bbox_ratios:
  - 0.2673
  - 0.4187
  - 0.5403
  - 0.6204
  frame: 15
  global_frame: 1742
  prompt: the caribou is walking
- bbox_ratios:
  - 0.2567
  - 0.4201
  - 0.5407
  - 0.6296
  frame: 16
  global_frame: 1743
  prompt: the caribou is walking
- bbox_ratios:
  - 0.2462
  - 0.4216
  - 0.541
  - 0.6389
  frame: 17
  global_frame: 1744
  prompt: the caribou is walking
- bbox_ratios:
  - 0.2356
  - 0.423
  - 0.5414
  - 0.6481
  frame: 18
  global_frame: 1745
  prompt: the caribou is walking
- bbox_ratios:
  - 0.225
  - 0.4244
  - 0.5417
  - 0.6574
  frame: 19
  global_frame: 1746
  prompt: the caribou is walking
- bbox_ratios:
  - 0.2145
  - 0.4259
  - 0.5421
  - 0.6666
  frame: 20
  global_frame: 1747
  prompt: the caribou is walking
- bbox_ratios:
  - 0.2039
  - 0.4273
  - 0.5424
  - 0.6759
  frame: 21
  global_frame: 1748
  prompt: the caribou is walking
- bbox_ratios:
  - 0.1934
  - 0.4288
  - 0.5428
  - 0.6851
  frame: 22
  global_frame: 1749
  prompt: the caribou is walking
- bbox_ratios:
  - 0.1828
  - 0.4302
  - 0.5431
  - 0.6944
  frame: 23
  global_frame: 1750
  prompt: the caribou is walking
motion_id: 26
motion_iter: 2
num_inference_steps: null
object_name: caribou
seed: 4
source_clip: HAOHQFGA_1087_1800
token_inds:
- 2
trailblazer:
  num_dd_spatial_steps: 5
  num_dd_temporal_steps: 5
  spatial_strengthen_scale: 0.15
  spatial_weaken_scale: 0.001
  temp_strengthen_scale: 0.15
  temp_weaken_scale: 0.001
  trailing_length: 15
width: 320
