height: 320
keyframe:
- bbox_ratios:
  - 0.0235
  - 0.4593
  - 0.5244
  - 0.8583
  frame: 0
  global_frame: 886
  prompt: the african civet is exploring
- bbox_ratios:
  - 0.0273
  - 0.4593
  - 0.5261
  - 0.8596
  frame: 1
  global_frame: 887
  prompt: the african civet is exploring
- bbox_ratios:
  - 0.0336
  - 0.4609
  - 0.5268
  - 0.8596
  frame: 2
  global_frame: 888
  prompt: the african civet is exploring
- bbox_ratios:
  - 0.0399
  - 0.4625
  - 0.5276
  - 0.8596
  frame: 3
  global_frame: 889
  prompt: the african civet is exploring
- bbox_ratios:
  - 0.0462
  - 0.4641
  - 0.5283
  - 0.8597
  frame: 4
  global_frame: 890
  prompt: the african civet is exploring
- bbox_ratios:
  - 0.0524
  - 0.4657
  - 0.529
  - 0.8597
  frame: 5
  global_frame: 891
  prompt: the african civet is exploring
- bbox_ratios:
  - 0.0587
  - 0.4672
  - 0.5297
  - 0.8597
  frame: 6
  global_frame: 892
  prompt: the african civet is exploring
- bbox_ratios:
  - 0.0588
  - 0.4683
  - 0.5304
  - 0.8599
  frame: 7
  global_frame: 893
  prompt: the african civet is exploring
- bbox_ratios:
  - 0.0793
  - 0.4816
  - 0.5259
  - 0.8589
  frame: 8
  global_frame: 894
  prompt: the african civet is exploring
- bbox_ratios:
  - 0.0828
  - 0.4808
  - 0.5226
  - 0.8539
  frame: 9
  global_frame: 895
  prompt: the african civet is exploring
- bbox_ratios:
  - 0.0939
  - 0.4985
  - 0.5361
  - 0.8571
  frame: 10
  global_frame: 896
  prompt: the african civet is exploring
- bbox_ratios:
  - 0.0942
  - 0.4976
  - 0.536
  - 0.8574
  frame: 11
  global_frame: 897
  prompt: the african civet is exploring
- bbox_ratios:
  - 0.1042
  - 0.5053
  - 0.5366
  - 0.858
  frame: 12
  global_frame: 898
  prompt: the african civet is exploring
- bbox_ratios:
  - 0.1142
  - 0.513
  - 0.5372
  - 0.8586
  frame: 13
  global_frame: 899
  prompt: the african civet is exploring
- bbox_ratios:
  - 0.1274
  - 0.5088
  - 0.5413
  - 0.8579
  frame: 14
  global_frame: 900
  prompt: the african civet is exploring
- bbox_ratios:
  - 0.1405
  - 0.5045
  - 0.5455
  - 0.8571
  frame: 15
  global_frame: 901
  prompt: the african civet is exploring
- bbox_ratios:
  - 0.1537
  - 0.5003
  - 0.5496
  - 0.8564
  frame: 16
  global_frame: 902
  prompt: the african civet is exploring
- bbox_ratios:
  - 0.1659
  - 0.4975
  - 0.5493
  - 0.8567
  frame: 17
  global_frame: 903
  prompt: the african civet is exploring
- bbox_ratios:
  - 0.1576
  - 0.5025
  - 0.5359
  - 0.8526
  frame: 18
  global_frame: 904
  prompt: the african civet is exploring
- bbox_ratios:
  - 0.1574
  - 0.5027
  - 0.5361
  - 0.8527
  frame: 19
  global_frame: 905
  prompt: the african civet is exploring
- bbox_ratios:
  - 0.1623
  - 0.4937
  - 0.5404
  - 0.8497
  frame: 20
  global_frame: 906
  prompt: the african civet is exploring
- bbox_ratios:
  - 0.1804
  - 0.4794
  - 0.5523
  - 0.8478
  frame: 21
  global_frame: 907
  prompt: the african civet is exploring
- bbox_ratios:
  - 0.178
  - 0.4908
  - 0.5395
  - 0.8531
  frame: 22
  global_frame: 908
  prompt: the african civet is exploring
- bbox_ratios:
  - 0.1775
  - 0.4903
  - 0.5397
  - 0.8532
  frame: 23
  global_frame: 909
  prompt: the african civet is exploring
motion_id: 86
motion_iter: 1
num_inference_steps: null
object_name: civet
seed: 4
source_clip: JZFDVTHG_676_928
token_inds:
- 3
trailblazer:
  num_dd_spatial_steps: 5
  num_dd_temporal_steps: 5
  spatial_strengthen_scale: 0.15
  spatial_weaken_scale: 0.001
  temp_strengthen_scale: 0.15
  temp_weaken_scale: 0.001
  trailing_length: 15
width: 320
