height: 320
keyframe:
- bbox_ratios:
  - 0.4014
  - 0.2749
  - 0.7132
  - 0.9926
  frame: 0
  global_frame: 568
  prompt: the nudibranch is moving
- bbox_ratios:
  - 0.4017
  - 0.2745
  - 0.7127
  - 0.9921
  frame: 1
  global_frame: 569
  prompt: the nudibranch is moving
- bbox_ratios:
  - 0.3814
  - 0.2758
  - 0.7079
  - 0.9904
  frame: 2
  global_frame: 570
  prompt: the nudibranch is moving
- bbox_ratios:
  - 0.3977
  - 0.2746
  - 0.7115
  - 0.9921
  frame: 3
  global_frame: 571
  prompt: the nudibranch is moving
- bbox_ratios:
  - 0.3935
  - 0.274
  - 0.7117
  - 0.9918
  frame: 4
  global_frame: 572
  prompt: the nudibranch is moving
- bbox_ratios:
  - 0.3945
  - 0.2713
  - 0.7127
  - 0.992
  frame: 5
  global_frame: 573
  prompt: the nudibranch is moving
- bbox_ratios:
  - 0.3954
  - 0.2716
  - 0.7121
  - 0.9919
  frame: 6
  global_frame: 574
  prompt: the nudibranch is moving
- bbox_ratios:
  - 0.3947
  - 0.2712
  - 0.7115
  - 0.9923
  frame: 7
  global_frame: 575
  prompt: the nudibranch is moving
- bbox_ratios:
  - 0.3937
  - 0.2695
  - 0.7116
  - 0.9924
  frame: 8
  global_frame: 576
  prompt: the nudibranch is moving
- bbox_ratios:
  - 0.3914
  - 0.2664
  - 0.7115
  - 0.9928
  frame: 9
  global_frame: 577
  prompt: the nudibranch is moving
- bbox_ratios:
  - 0.3912
  - 0.264
  - 0.7107
  - 0.9922
  frame: 10
  global_frame: 578
  prompt: the nudibranch is moving
- bbox_ratios:
  - 0.3913
  - 0.2622
  - 0.7109
  - 0.9928
  frame: 11
  global_frame: 579
  prompt: the nudibranch is moving
- bbox_ratios:
  - 0.3925
  - 0.2617
  - 0.7104
  - 0.9927
  frame: 12
  global_frame: 580
  prompt: the nudibranch is moving
- bbox_ratios:
  - 0.3928
  - 0.2598
  - 0.7108
  - 0.9928
  frame: 13
  global_frame: 581
  prompt: the nudibranch is moving
- bbox_ratios:
  - 0.3932
  - 0.2579
  - 0.7113
  - 0.993
  frame: 14
  global_frame: 582
  prompt: the nudibranch is moving
- bbox_ratios:
  - 0.3935
  - 0.256
  - 0.7118
  - 0.9931
  frame: 15
  global_frame: 583
  prompt: the nudibranch is moving
- bbox_ratios:
  - 0.3931
  - 0.2557
  - 0.7122
  - 0.9929
  frame: 16
  global_frame: 584
  prompt: the nudibranch is moving
- bbox_ratios:
  - 0.3935
  - 0.2564
  - 0.7129
  - 0.993
  frame: 17
  global_frame: 585
  prompt: the nudibranch is moving
- bbox_ratios:
  - 0.3925
  - 0.2547
  - 0.714
  - 0.9925
  frame: 18
  global_frame: 586
  prompt: the nudibranch is moving
- bbox_ratios:
  - 0.3919
  - 0.2531
  - 0.7143
  - 0.9928
  frame: 19
  global_frame: 587
  prompt: the nudibranch is moving
- bbox_ratios:
  - 0.3914
  - 0.2543
  - 0.7143
  - 0.9932
  frame: 20
  global_frame: 588
  prompt: the nudibranch is moving
- bbox_ratios:
  - 0.391
  - 0.2536
  - 0.7145
  - 0.9928
  frame: 21
  global_frame: 589
  prompt: the nudibranch is moving
- bbox_ratios:
  - 0.3905
  - 0.2548
  - 0.7152
  - 0.9932
  frame: 22
  global_frame: 590
  prompt: the nudibranch is moving
- bbox_ratios:
  - 0.3912
  - 0.2565
  - 0.7151
  - 0.9937
  frame: 23
  global_frame: 591
  prompt: the nudibranch is moving
motion_id: 2
motion_iter: 1
num_inference_steps: null
object_name: nudibranch
seed: 4
source_clip: NLZCUQDT_523_686
token_inds:
- 2
trailblazer:
  num_dd_spatial_steps: 5
  num_dd_temporal_steps: 5
  spatial_strengthen_scale: 0.15
  spatial_weaken_scale: 0.001
  temp_strengthen_scale: 0.15
  temp_weaken_scale: 0.001
  trailing_length: 15
width: 320
