height: 320
keyframe:
- bbox_ratios:
  - 0.1156
  - 0.0015
  - 0.9274
  - 0.9971
  frame: 0
  global_frame: 162
  prompt: the bumblebee is flying
- bbox_ratios:
  - 0.1155
  - 0.0014
  - 0.9234
  - 0.9969
  frame: 1
  global_frame: 163
  prompt: the bumblebee is flying
- bbox_ratios:
  - 0.1166
  - -0.0
  - 0.8482
  - 0.9943
  frame: 2
  global_frame: 164
  prompt: the bumblebee is flying
- bbox_ratios:
  - 0.1171
  - -0.0022
  - 0.9291
  - 0.9913
  frame: 3
  global_frame: 165
  prompt: the bumblebee is flying
- bbox_ratios:
  - 0.1193
  - -0.0017
  - 0.9381
  - 0.9919
  frame: 4
  global_frame: 166
  prompt: the bumblebee is flying
- bbox_ratios:
  - 0.1215
  - -0.0012
  - 0.947
  - 0.9924
  frame: 5
  global_frame: 167
  prompt: the bumblebee is flying
- bbox_ratios:
  - 0.1184
  - -0.0009
  - 0.9242
  - 0.9927
  frame: 6
  global_frame: 168
  prompt: the bumblebee is flying
- bbox_ratios:
  - 0.1152
  - -0.0006
  - 0.9013
  - 0.9929
  frame: 7
  global_frame: 169
  prompt: the bumblebee is flying
- bbox_ratios:
  - 0.128
  - 0.002
  - 0.9148
  - 0.9952
  frame: 8
  global_frame: 170
  prompt: the bumblebee is flying
- bbox_ratios:
  - 0.1267
  - -0.0018
  - 0.9627
  - 0.9918
  frame: 9
  global_frame: 171
  prompt: the bumblebee is flying
- bbox_ratios:
  - 0.1261
  - 0.0058
  - 0.9412
  - 0.9951
  frame: 10
  global_frame: 172
  prompt: the bumblebee is flying
- bbox_ratios:
  - 0.1241
  - 0.0059
  - 0.9517
  - 0.9966
  frame: 11
  global_frame: 173
  prompt: the bumblebee is flying
- bbox_ratios:
  - 0.1221
  - 0.006
  - 0.9622
  - 0.998
  frame: 12
  global_frame: 174
  prompt: the bumblebee is flying
- bbox_ratios:
  - 0.1241
  - 0.0014
  - 0.9462
  - 0.9957
  frame: 13
  global_frame: 175
  prompt: the bumblebee is flying
- bbox_ratios:
  - 0.1159
  - 0.0011
  - 0.9176
  - 0.9958
  frame: 14
  global_frame: 176
  prompt: the bumblebee is flying
- bbox_ratios:
  - 0.1175
  - 0.0026
  - 0.9195
  - 0.9973
  frame: 15
  global_frame: 177
  prompt: the bumblebee is flying
- bbox_ratios:
  - 0.1191
  - 0.0042
  - 0.9214
  - 0.9987
  frame: 16
  global_frame: 178
  prompt: the bumblebee is flying
- bbox_ratios:
  - 0.1163
  - 0.0026
  - 0.9286
  - 0.9977
  frame: 17
  global_frame: 179
  prompt: the bumblebee is flying
- bbox_ratios:
  - 0.1273
  - -0.0024
  - 0.8928
  - 0.9921
  frame: 18
  global_frame: 180
  prompt: the bumblebee is flying
- bbox_ratios:
  - 0.1261
  - 0.0053
  - 0.9022
  - 0.9988
  frame: 19
  global_frame: 181
  prompt: the bumblebee is flying
- bbox_ratios:
  - 0.123
  - 0.0052
  - 0.894
  - 0.9991
  frame: 20
  global_frame: 182
  prompt: the bumblebee is flying
- bbox_ratios:
  - 0.1198
  - 0.0051
  - 0.8858
  - 0.9994
  frame: 21
  global_frame: 183
  prompt: the bumblebee is flying
- bbox_ratios:
  - 0.1167
  - 0.0049
  - 0.8776
  - 0.9996
  frame: 22
  global_frame: 184
  prompt: the bumblebee is flying
- bbox_ratios:
  - 0.1135
  - 0.0048
  - 0.8693
  - 0.9999
  frame: 23
  global_frame: 185
  prompt: the bumblebee is flying
motion_id: 159
motion_iter: 1
num_inference_steps: null
object_name: bumblebee
seed: 4
source_clip: EJEJXHPH_2_189
token_inds:
- 2
trailblazer:
  num_dd_spatial_steps: 5
  num_dd_temporal_steps: 5
  spatial_strengthen_scale: 0.15
  spatial_weaken_scale: 0.001
  temp_strengthen_scale: 0.15
  temp_weaken_scale: 0.001
  trailing_length: 15
width: 320
