height: 320
keyframe:
- bbox_ratios:
  - 0.2628
  - 0.6605
  - 0.6006
  - 0.9314
  frame: 0
  global_frame: 299
  prompt: the fox is jumping
- bbox_ratios:
  - 0.2684
  - 0.6779
  - 0.5767
  - 0.9367
  frame: 1
  global_frame: 300
  prompt: the fox is jumping
- bbox_ratios:
  - 0.0773
  - 0.6801
  - 0.6244
  - 0.9457
  frame: 2
  global_frame: 301
  prompt: the fox is jumping
- bbox_ratios:
  - 0.0926
  - 0.6856
  - 0.6272
  - 0.9448
  frame: 3
  global_frame: 302
  prompt: the fox is jumping
- bbox_ratios:
  - 0.1312
  - 0.6614
  - 0.6399
  - 0.9377
  frame: 4
  global_frame: 303
  prompt: the fox is jumping
- bbox_ratios:
  - 0.1306
  - 0.6616
  - 0.6398
  - 0.9378
  frame: 5
  global_frame: 304
  prompt: the fox is jumping
- bbox_ratios:
  - 0.1189
  - 0.619
  - 0.6534
  - 0.9409
  frame: 6
  global_frame: 305
  prompt: the fox is jumping
- bbox_ratios:
  - 0.1313
  - 0.5744
  - 0.6664
  - 0.9401
  frame: 7
  global_frame: 306
  prompt: the fox is jumping
- bbox_ratios:
  - 0.1255
  - 0.5103
  - 0.6684
  - 0.9451
  frame: 8
  global_frame: 307
  prompt: the fox is jumping
- bbox_ratios:
  - 0.1424
  - 0.454
  - 0.6903
  - 0.951
  frame: 9
  global_frame: 308
  prompt: the fox is jumping
- bbox_ratios:
  - 0.1415
  - 0.4545
  - 0.6899
  - 0.9513
  frame: 10
  global_frame: 309
  prompt: the fox is jumping
- bbox_ratios:
  - 0.1491
  - 0.4077
  - 0.7063
  - 0.9382
  frame: 11
  global_frame: 310
  prompt: the fox is jumping
- bbox_ratios:
  - 0.1758
  - 0.3783
  - 0.7373
  - 0.9352
  frame: 12
  global_frame: 311
  prompt: the fox is jumping
- bbox_ratios:
  - 0.2008
  - 0.3429
  - 0.7565
  - 0.9266
  frame: 13
  global_frame: 312
  prompt: the fox is jumping
- bbox_ratios:
  - 0.225
  - 0.332
  - 0.7725
  - 0.9333
  frame: 14
  global_frame: 313
  prompt: the fox is jumping
- bbox_ratios:
  - 0.2253
  - 0.3322
  - 0.772
  - 0.9333
  frame: 15
  global_frame: 314
  prompt: the fox is jumping
- bbox_ratios:
  - 0.2536
  - 0.3073
  - 0.7918
  - 0.929
  frame: 16
  global_frame: 315
  prompt: the fox is jumping
- bbox_ratios:
  - 0.2819
  - 0.2824
  - 0.8115
  - 0.9247
  frame: 17
  global_frame: 316
  prompt: the fox is jumping
- bbox_ratios:
  - 0.286
  - 0.2642
  - 0.8248
  - 0.9094
  frame: 18
  global_frame: 317
  prompt: the fox is jumping
- bbox_ratios:
  - 0.2901
  - 0.246
  - 0.8381
  - 0.8941
  frame: 19
  global_frame: 318
  prompt: the fox is jumping
- bbox_ratios:
  - 0.2942
  - 0.2278
  - 0.8514
  - 0.8788
  frame: 20
  global_frame: 319
  prompt: the fox is jumping
- bbox_ratios:
  - 0.2983
  - 0.2096
  - 0.8647
  - 0.8636
  frame: 21
  global_frame: 320
  prompt: the fox is jumping
- bbox_ratios:
  - 0.2968
  - 0.195
  - 0.8773
  - 0.8439
  frame: 22
  global_frame: 321
  prompt: the fox is jumping
- bbox_ratios:
  - 0.2981
  - 0.1765
  - 0.8932
  - 0.8102
  frame: 23
  global_frame: 322
  prompt: the fox is jumping
motion_id: 114
motion_iter: 2
num_inference_steps: null
object_name: fox
seed: 4
source_clip: CMUPTEBY_156_372
token_inds:
- 2
trailblazer:
  num_dd_spatial_steps: 5
  num_dd_temporal_steps: 5
  spatial_strengthen_scale: 0.15
  spatial_weaken_scale: 0.001
  temp_strengthen_scale: 0.15
  temp_weaken_scale: 0.001
  trailing_length: 15
width: 320
