height: 320
keyframe:
- bbox_ratios:
  - 0.0078
  - 0.0019
  - 0.8664
  - 0.9987
  frame: 0
  global_frame: 1071
  prompt: the lobster is swimming
- bbox_ratios:
  - 0.0013
  - 0.0026
  - 0.8383
  - 0.9978
  frame: 1
  global_frame: 1072
  prompt: the lobster is swimming
- bbox_ratios:
  - 0.0027
  - 0.002
  - 0.835
  - 0.9988
  frame: 2
  global_frame: 1073
  prompt: the lobster is swimming
- bbox_ratios:
  - 0.009
  - 0.0037
  - 0.8361
  - 1.001
  frame: 3
  global_frame: 1074
  prompt: the lobster is swimming
- bbox_ratios:
  - 0.0027
  - -0.0002
  - 0.839
  - 0.995
  frame: 4
  global_frame: 1075
  prompt: the lobster is swimming
- bbox_ratios:
  - 0.0051
  - -0.0047
  - 0.8247
  - 0.9909
  frame: 5
  global_frame: 1076
  prompt: the lobster is swimming
- bbox_ratios:
  - 0.0029
  - 0.0018
  - 0.8267
  - 0.997
  frame: 6
  global_frame: 1077
  prompt: the lobster is swimming
- bbox_ratios:
  - -0.0027
  - 0.0012
  - 0.8215
  - 0.9975
  frame: 7
  global_frame: 1078
  prompt: the lobster is swimming
- bbox_ratios:
  - 0.0062
  - 0.0024
  - 0.8276
  - 0.999
  frame: 8
  global_frame: 1079
  prompt: the lobster is swimming
- bbox_ratios:
  - 0.0078
  - 0.0074
  - 0.8192
  - 1.0029
  frame: 9
  global_frame: 1080
  prompt: the lobster is swimming
- bbox_ratios:
  - -0.0008
  - 0.0053
  - 0.8199
  - 1.0007
  frame: 10
  global_frame: 1081
  prompt: the lobster is swimming
- bbox_ratios:
  - 0.0096
  - 0.0019
  - 0.8315
  - 0.9986
  frame: 11
  global_frame: 1082
  prompt: the lobster is swimming
- bbox_ratios:
  - -0.0115
  - 0.0106
  - 0.8127
  - 1.0081
  frame: 12
  global_frame: 1083
  prompt: the lobster is swimming
- bbox_ratios:
  - 0.0002
  - -0.0005
  - 0.8129
  - 0.9954
  frame: 13
  global_frame: 1084
  prompt: the lobster is swimming
- bbox_ratios:
  - 0.0042
  - 0.0066
  - 0.8076
  - 1.0015
  frame: 14
  global_frame: 1085
  prompt: the lobster is swimming
- bbox_ratios:
  - -0.0092
  - 0.005
  - 0.7882
  - 1.0023
  frame: 15
  global_frame: 1086
  prompt: the lobster is swimming
- bbox_ratios:
  - 0.0172
  - -0.0016
  - 0.7925
  - 0.9942
  frame: 16
  global_frame: 1087
  prompt: the lobster is swimming
- bbox_ratios:
  - -0.0025
  - 0.0035
  - 0.7715
  - 1.0012
  frame: 17
  global_frame: 1088
  prompt: the lobster is swimming
- bbox_ratios:
  - -0.0055
  - -0.0009
  - 0.7736
  - 0.9968
  frame: 18
  global_frame: 1089
  prompt: the lobster is swimming
- bbox_ratios:
  - -0.0043
  - 0.0062
  - 0.7455
  - 1.0028
  frame: 19
  global_frame: 1090
  prompt: the lobster is swimming
- bbox_ratios:
  - -0.0021
  - -0.0006
  - 0.7453
  - 0.9968
  frame: 20
  global_frame: 1091
  prompt: the lobster is swimming
- bbox_ratios:
  - -0.0015
  - -0.0012
  - 0.7289
  - 0.9962
  frame: 21
  global_frame: 1092
  prompt: the lobster is swimming
- bbox_ratios:
  - -0.0012
  - 0.0004
  - 0.7274
  - 0.9973
  frame: 22
  global_frame: 1093
  prompt: the lobster is swimming
- bbox_ratios:
  - -0.0034
  - 0.0034
  - 0.7304
  - 1.0008
  frame: 23
  global_frame: 1094
  prompt: the lobster is swimming
motion_id: 8
motion_iter: 0
num_inference_steps: null
object_name: lobster
seed: 4
source_clip: DTDZIXEV_1063_1096
token_inds:
- 2
trailblazer:
  num_dd_spatial_steps: 5
  num_dd_temporal_steps: 5
  spatial_strengthen_scale: 0.15
  spatial_weaken_scale: 0.001
  temp_strengthen_scale: 0.15
  temp_weaken_scale: 0.001
  trailing_length: 15
width: 320
