height: 320
keyframe:
- bbox_ratios:
  - 0.1213
  - -0.0037
  - 0.7744
  - 0.9935
  frame: 0
  global_frame: 228
  prompt: the pufferfish is swimming
- bbox_ratios:
  - 0.1928
  - -0.0046
  - 0.7771
  - 0.9935
  frame: 1
  global_frame: 229
  prompt: the pufferfish is swimming
- bbox_ratios:
  - 0.2862
  - 0.0018
  - 0.779
  - 0.9894
  frame: 2
  global_frame: 230
  prompt: the pufferfish is swimming
- bbox_ratios:
  - 0.3724
  - 0.0541
  - 0.7891
  - 0.9926
  frame: 3
  global_frame: 231
  prompt: the pufferfish is swimming
- bbox_ratios:
  - 0.3724
  - 0.0541
  - 0.7891
  - 0.9925
  frame: 4
  global_frame: 232
  prompt: the pufferfish is swimming
- bbox_ratios:
  - 0.382
  - 0.0894
  - 0.8402
  - 0.9977
  frame: 5
  global_frame: 233
  prompt: the pufferfish is swimming
- bbox_ratios:
  - 0.3652
  - 0.0819
  - 0.9407
  - 0.9995
  frame: 6
  global_frame: 234
  prompt: the pufferfish is swimming
- bbox_ratios:
  - 0.3517
  - 0.0781
  - 0.9437
  - 0.9994
  frame: 7
  global_frame: 235
  prompt: the pufferfish is swimming
- bbox_ratios:
  - 0.3382
  - 0.0743
  - 0.9467
  - 0.9994
  frame: 8
  global_frame: 236
  prompt: the pufferfish is swimming
- bbox_ratios:
  - 0.3247
  - 0.0705
  - 0.9497
  - 0.9993
  frame: 9
  global_frame: 237
  prompt: the pufferfish is swimming
- bbox_ratios:
  - 0.3113
  - 0.0667
  - 0.9528
  - 0.9993
  frame: 10
  global_frame: 238
  prompt: the pufferfish is swimming
- bbox_ratios:
  - 0.2978
  - 0.0629
  - 0.9558
  - 0.9992
  frame: 11
  global_frame: 239
  prompt: the pufferfish is swimming
- bbox_ratios:
  - 0.2843
  - 0.0591
  - 0.9588
  - 0.9992
  frame: 12
  global_frame: 240
  prompt: the pufferfish is swimming
- bbox_ratios:
  - 0.2708
  - 0.0553
  - 0.9618
  - 0.9991
  frame: 13
  global_frame: 241
  prompt: the pufferfish is swimming
- bbox_ratios:
  - 0.2573
  - 0.0515
  - 0.9649
  - 0.9991
  frame: 14
  global_frame: 242
  prompt: the pufferfish is swimming
- bbox_ratios:
  - 0.2438
  - 0.0477
  - 0.9679
  - 0.999
  frame: 15
  global_frame: 243
  prompt: the pufferfish is swimming
- bbox_ratios:
  - 0.2303
  - 0.0439
  - 0.9709
  - 0.999
  frame: 16
  global_frame: 244
  prompt: the pufferfish is swimming
- bbox_ratios:
  - 0.2168
  - 0.0401
  - 0.9739
  - 0.9989
  frame: 17
  global_frame: 245
  prompt: the pufferfish is swimming
- bbox_ratios:
  - 0.2033
  - 0.0363
  - 0.977
  - 0.9989
  frame: 18
  global_frame: 246
  prompt: the pufferfish is swimming
- bbox_ratios:
  - 0.1898
  - 0.0325
  - 0.98
  - 0.9988
  frame: 19
  global_frame: 247
  prompt: the pufferfish is swimming
- bbox_ratios:
  - 0.1763
  - 0.0287
  - 0.983
  - 0.9988
  frame: 20
  global_frame: 248
  prompt: the pufferfish is swimming
- bbox_ratios:
  - 0.1629
  - 0.0249
  - 0.986
  - 0.9987
  frame: 21
  global_frame: 249
  prompt: the pufferfish is swimming
- bbox_ratios:
  - 0.1494
  - 0.0211
  - 0.9891
  - 0.9986
  frame: 22
  global_frame: 250
  prompt: the pufferfish is swimming
- bbox_ratios:
  - 0.1359
  - 0.0173
  - 0.9921
  - 0.9986
  frame: 23
  global_frame: 251
  prompt: the pufferfish is swimming
motion_id: 0
motion_iter: 0
num_inference_steps: null
object_name: pufferfish
seed: 4
source_clip: IACOTNPL_208_280
token_inds:
- 2
trailblazer:
  num_dd_spatial_steps: 5
  num_dd_temporal_steps: 5
  spatial_strengthen_scale: 0.15
  spatial_weaken_scale: 0.001
  temp_strengthen_scale: 0.15
  temp_weaken_scale: 0.001
  trailing_length: 15
width: 320
