height: 320
keyframe:
- bbox_ratios:
  - 0.0108
  - -0.0014
  - 0.865
  - 0.9923
  frame: 0
  global_frame: 502
  prompt: the squirrel is walking
- bbox_ratios:
  - 0.0112
  - 0.0002
  - 0.8533
  - 0.9923
  frame: 1
  global_frame: 503
  prompt: the squirrel is walking
- bbox_ratios:
  - 0.0022
  - 0.0004
  - 0.8411
  - 0.9949
  frame: 2
  global_frame: 504
  prompt: the squirrel is walking
- bbox_ratios:
  - 0.0018
  - 0.0003
  - 0.8411
  - 0.9949
  frame: 3
  global_frame: 505
  prompt: the squirrel is walking
- bbox_ratios:
  - 0.0059
  - 0.0036
  - 0.8326
  - 0.9967
  frame: 4
  global_frame: 506
  prompt: the squirrel is walking
- bbox_ratios:
  - 0.0026
  - 0.0077
  - 0.8317
  - 1.002
  frame: 5
  global_frame: 507
  prompt: the squirrel is walking
- bbox_ratios:
  - 0.0023
  - 0.0065
  - 0.8326
  - 1.0012
  frame: 6
  global_frame: 508
  prompt: the squirrel is walking
- bbox_ratios:
  - 0.0031
  - 0.006
  - 0.8324
  - 1.0004
  frame: 7
  global_frame: 509
  prompt: the squirrel is walking
- bbox_ratios:
  - 0.0037
  - 0.0065
  - 0.8306
  - 1.0008
  frame: 8
  global_frame: 510
  prompt: the squirrel is walking
- bbox_ratios:
  - 0.0032
  - 0.0065
  - 0.8302
  - 1.001
  frame: 9
  global_frame: 511
  prompt: the squirrel is walking
- bbox_ratios:
  - 0.0044
  - 0.0069
  - 0.8295
  - 1.0008
  frame: 10
  global_frame: 512
  prompt: the squirrel is walking
- bbox_ratios:
  - 0.0031
  - 0.0061
  - 0.8291
  - 0.9999
  frame: 11
  global_frame: 513
  prompt: the squirrel is walking
- bbox_ratios:
  - 0.0037
  - 0.0044
  - 0.8291
  - 0.9985
  frame: 12
  global_frame: 514
  prompt: the squirrel is walking
- bbox_ratios:
  - 0.0039
  - 0.0056
  - 0.8272
  - 0.9998
  frame: 13
  global_frame: 515
  prompt: the squirrel is walking
- bbox_ratios:
  - 0.0042
  - 0.0057
  - 0.8277
  - 1.0001
  frame: 14
  global_frame: 516
  prompt: the squirrel is walking
- bbox_ratios:
  - 0.0043
  - 0.0058
  - 0.8274
  - 1.0002
  frame: 15
  global_frame: 517
  prompt: the squirrel is walking
- bbox_ratios:
  - 0.0039
  - 0.0056
  - 0.8275
  - 0.9999
  frame: 16
  global_frame: 518
  prompt: the squirrel is walking
- bbox_ratios:
  - 0.004
  - 0.0053
  - 0.8275
  - 0.9997
  frame: 17
  global_frame: 519
  prompt: the squirrel is walking
- bbox_ratios:
  - 0.0033
  - 0.0048
  - 0.8277
  - 0.9992
  frame: 18
  global_frame: 520
  prompt: the squirrel is walking
- bbox_ratios:
  - 0.004
  - 0.0047
  - 0.8272
  - 0.9992
  frame: 19
  global_frame: 521
  prompt: the squirrel is walking
- bbox_ratios:
  - 0.0037
  - 0.0049
  - 0.8272
  - 0.9995
  frame: 20
  global_frame: 522
  prompt: the squirrel is walking
- bbox_ratios:
  - 0.0044
  - 0.0051
  - 0.8277
  - 0.9996
  frame: 21
  global_frame: 523
  prompt: the squirrel is walking
- bbox_ratios:
  - 0.0043
  - 0.005
  - 0.8273
  - 0.9995
  frame: 22
  global_frame: 524
  prompt: the squirrel is walking
- bbox_ratios:
  - 0.0043
  - 0.0052
  - 0.8276
  - 0.9995
  frame: 23
  global_frame: 525
  prompt: the squirrel is walking
motion_id: 2
motion_iter: 1
num_inference_steps: null
object_name: squirrel
seed: 4
source_clip: BBQCYNPL_448_542
token_inds:
- 2
trailblazer:
  num_dd_spatial_steps: 5
  num_dd_temporal_steps: 5
  spatial_strengthen_scale: 0.15
  spatial_weaken_scale: 0.001
  temp_strengthen_scale: 0.15
  temp_weaken_scale: 0.001
  trailing_length: 15
width: 320
