height: 320
keyframe:
- bbox_ratios:
  - 0.4422
  - 0.2503
  - 0.9454
  - 0.8787
  frame: 0
  global_frame: 192
  prompt: the marine iguana is running
- bbox_ratios:
  - 0.4231
  - 0.2661
  - 0.9467
  - 0.9052
  frame: 1
  global_frame: 193
  prompt: the marine iguana is running
- bbox_ratios:
  - 0.4039
  - 0.2818
  - 0.948
  - 0.9318
  frame: 2
  global_frame: 194
  prompt: the marine iguana is running
- bbox_ratios:
  - 0.447
  - 0.2896
  - 0.9612
  - 0.9224
  frame: 3
  global_frame: 195
  prompt: the marine iguana is running
- bbox_ratios:
  - 0.49
  - 0.2973
  - 0.9744
  - 0.913
  frame: 4
  global_frame: 196
  prompt: the marine iguana is running
- bbox_ratios:
  - 0.5331
  - 0.3051
  - 0.9876
  - 0.9036
  frame: 5
  global_frame: 197
  prompt: the marine iguana is running
- bbox_ratios:
  - 0.5762
  - 0.3129
  - 1.0008
  - 0.8942
  frame: 6
  global_frame: 198
  prompt: the marine iguana is running
- bbox_ratios:
  - 0.5715
  - 0.3202
  - 1.0015
  - 0.9116
  frame: 7
  global_frame: 199
  prompt: the marine iguana is running
- bbox_ratios:
  - 0.5669
  - 0.3276
  - 1.0021
  - 0.929
  frame: 8
  global_frame: 200
  prompt: the marine iguana is running
- bbox_ratios:
  - 0.5623
  - 0.335
  - 1.0027
  - 0.9464
  frame: 9
  global_frame: 201
  prompt: the marine iguana is running
- bbox_ratios:
  - 0.5577
  - 0.3423
  - 1.0033
  - 0.9638
  frame: 10
  global_frame: 202
  prompt: the marine iguana is running
- bbox_ratios:
  - 0.5433
  - 0.3532
  - 1.0003
  - 0.9633
  frame: 11
  global_frame: 203
  prompt: the marine iguana is running
- bbox_ratios:
  - 0.5289
  - 0.364
  - 0.9972
  - 0.9629
  frame: 12
  global_frame: 204
  prompt: the marine iguana is running
- bbox_ratios:
  - 0.5145
  - 0.3749
  - 0.9942
  - 0.9624
  frame: 13
  global_frame: 205
  prompt: the marine iguana is running
- bbox_ratios:
  - 0.5001
  - 0.3857
  - 0.9912
  - 0.9619
  frame: 14
  global_frame: 206
  prompt: the marine iguana is running
- bbox_ratios:
  - 0.4858
  - 0.3966
  - 0.9881
  - 0.9614
  frame: 15
  global_frame: 207
  prompt: the marine iguana is running
- bbox_ratios:
  - 0.4714
  - 0.4074
  - 0.9851
  - 0.961
  frame: 16
  global_frame: 208
  prompt: the marine iguana is running
- bbox_ratios:
  - 0.457
  - 0.4182
  - 0.9821
  - 0.9605
  frame: 17
  global_frame: 209
  prompt: the marine iguana is running
- bbox_ratios:
  - 0.4426
  - 0.4291
  - 0.979
  - 0.96
  frame: 18
  global_frame: 210
  prompt: the marine iguana is running
- bbox_ratios:
  - 0.4282
  - 0.4399
  - 0.976
  - 0.9596
  frame: 19
  global_frame: 211
  prompt: the marine iguana is running
- bbox_ratios:
  - 0.4138
  - 0.4508
  - 0.9729
  - 0.9591
  frame: 20
  global_frame: 212
  prompt: the marine iguana is running
- bbox_ratios:
  - 0.3995
  - 0.4616
  - 0.9699
  - 0.9586
  frame: 21
  global_frame: 213
  prompt: the marine iguana is running
- bbox_ratios:
  - 0.3851
  - 0.4725
  - 0.9669
  - 0.9581
  frame: 22
  global_frame: 214
  prompt: the marine iguana is running
- bbox_ratios:
  - 0.3707
  - 0.4833
  - 0.9638
  - 0.9577
  frame: 23
  global_frame: 215
  prompt: the marine iguana is running
motion_id: 97
motion_iter: 1
num_inference_steps: null
object_name: iguana
seed: 4
source_clip: AIICZDSN_64_249
token_inds:
- 3
trailblazer:
  num_dd_spatial_steps: 5
  num_dd_temporal_steps: 5
  spatial_strengthen_scale: 0.15
  spatial_weaken_scale: 0.001
  temp_strengthen_scale: 0.15
  temp_weaken_scale: 0.001
  trailing_length: 15
width: 320
