height: 320
keyframe:
- bbox_ratios:
  - 0.0733
  - 0.6418
  - 0.2539
  - 0.9731
  frame: 0
  global_frame: 195
  prompt: the california newt is moving
- bbox_ratios:
  - 0.0876
  - 0.5956
  - 0.3039
  - 0.9723
  frame: 1
  global_frame: 196
  prompt: the california newt is moving
- bbox_ratios:
  - 0.1018
  - 0.5493
  - 0.354
  - 0.9715
  frame: 2
  global_frame: 197
  prompt: the california newt is moving
- bbox_ratios:
  - 0.1161
  - 0.5031
  - 0.4041
  - 0.9707
  frame: 3
  global_frame: 198
  prompt: the california newt is moving
- bbox_ratios:
  - 0.1303
  - 0.4569
  - 0.4542
  - 0.9699
  frame: 4
  global_frame: 199
  prompt: the california newt is moving
- bbox_ratios:
  - 0.1446
  - 0.4107
  - 0.5042
  - 0.9691
  frame: 5
  global_frame: 200
  prompt: the california newt is moving
- bbox_ratios:
  - 0.1588
  - 0.3644
  - 0.5543
  - 0.9683
  frame: 6
  global_frame: 201
  prompt: the california newt is moving
- bbox_ratios:
  - 0.1731
  - 0.3182
  - 0.6044
  - 0.9675
  frame: 7
  global_frame: 202
  prompt: the california newt is moving
- bbox_ratios:
  - 0.1873
  - 0.272
  - 0.6545
  - 0.9667
  frame: 8
  global_frame: 203
  prompt: the california newt is moving
- bbox_ratios:
  - 0.2015
  - 0.2258
  - 0.7046
  - 0.9659
  frame: 9
  global_frame: 204
  prompt: the california newt is moving
- bbox_ratios:
  - 0.2158
  - 0.1795
  - 0.7546
  - 0.9651
  frame: 10
  global_frame: 205
  prompt: the california newt is moving
- bbox_ratios:
  - 0.23
  - 0.1333
  - 0.8047
  - 0.9642
  frame: 11
  global_frame: 206
  prompt: the california newt is moving
- bbox_ratios:
  - 0.2443
  - 0.0871
  - 0.8548
  - 0.9634
  frame: 12
  global_frame: 207
  prompt: the california newt is moving
- bbox_ratios:
  - 0.2585
  - 0.0409
  - 0.9049
  - 0.9626
  frame: 13
  global_frame: 208
  prompt: the california newt is moving
- bbox_ratios:
  - 0.2728
  - -0.0054
  - 0.955
  - 0.9618
  frame: 14
  global_frame: 209
  prompt: the california newt is moving
- bbox_ratios:
  - 0.2743
  - -0.0101
  - 0.9684
  - 0.9749
  frame: 15
  global_frame: 210
  prompt: the california newt is moving
- bbox_ratios:
  - 0.3997
  - -0.0068
  - 0.7856
  - 0.985
  frame: 16
  global_frame: 211
  prompt: the california newt is moving
- bbox_ratios:
  - 0.3991
  - -0.0042
  - 0.8154
  - 0.9882
  frame: 17
  global_frame: 212
  prompt: the california newt is moving
- bbox_ratios:
  - 0.3984
  - -0.0015
  - 0.8452
  - 0.9914
  frame: 18
  global_frame: 213
  prompt: the california newt is moving
- bbox_ratios:
  - 0.4069
  - -0.002
  - 0.875
  - 0.9841
  frame: 19
  global_frame: 214
  prompt: the california newt is moving
- bbox_ratios:
  - 0.4035
  - -0.006
  - 0.866
  - 0.9855
  frame: 20
  global_frame: 215
  prompt: the california newt is moving
- bbox_ratios:
  - 0.3869
  - 0.016
  - 0.8096
  - 0.9933
  frame: 21
  global_frame: 216
  prompt: the california newt is moving
- bbox_ratios:
  - 0.3592
  - -0.0038
  - 0.9002
  - 0.9902
  frame: 22
  global_frame: 217
  prompt: the california newt is moving
- bbox_ratios:
  - 0.3473
  - 0.0101
  - 0.8213
  - 0.9849
  frame: 23
  global_frame: 218
  prompt: the california newt is moving
motion_id: 1
motion_iter: 1
num_inference_steps: null
object_name: newt
seed: 4
source_clip: AJAWWQFB_136_271
token_inds:
- 3
trailblazer:
  num_dd_spatial_steps: 5
  num_dd_temporal_steps: 5
  spatial_strengthen_scale: 0.15
  spatial_weaken_scale: 0.001
  temp_strengthen_scale: 0.15
  temp_weaken_scale: 0.001
  trailing_length: 15
width: 320
