height: 320
keyframe:
- bbox_ratios:
  - 0.5072
  - 0.268
  - 0.8176
  - 0.792
  frame: 0
  global_frame: 189
  prompt: the tiger is walking
- bbox_ratios:
  - 0.5075
  - 0.2665
  - 0.8212
  - 0.7942
  frame: 1
  global_frame: 190
  prompt: the tiger is walking
- bbox_ratios:
  - 0.5061
  - 0.2645
  - 0.8278
  - 0.7991
  frame: 2
  global_frame: 191
  prompt: the tiger is walking
- bbox_ratios:
  - 0.5079
  - 0.2631
  - 0.8307
  - 0.8007
  frame: 3
  global_frame: 192
  prompt: the tiger is walking
- bbox_ratios:
  - 0.5057
  - 0.2546
  - 0.8347
  - 0.7965
  frame: 4
  global_frame: 193
  prompt: the tiger is walking
- bbox_ratios:
  - 0.5066
  - 0.2485
  - 0.8426
  - 0.7962
  frame: 5
  global_frame: 194
  prompt: the tiger is walking
- bbox_ratios:
  - 0.5081
  - 0.2473
  - 0.8462
  - 0.7977
  frame: 6
  global_frame: 195
  prompt: the tiger is walking
- bbox_ratios:
  - 0.5057
  - 0.2497
  - 0.8449
  - 0.7956
  frame: 7
  global_frame: 196
  prompt: the tiger is walking
- bbox_ratios:
  - 0.51
  - 0.2414
  - 0.8584
  - 0.7971
  frame: 8
  global_frame: 197
  prompt: the tiger is walking
- bbox_ratios:
  - 0.5082
  - 0.2391
  - 0.8568
  - 0.7975
  frame: 9
  global_frame: 198
  prompt: the tiger is walking
- bbox_ratios:
  - 0.5037
  - 0.2364
  - 0.8693
  - 0.7965
  frame: 10
  global_frame: 199
  prompt: the tiger is walking
- bbox_ratios:
  - 0.506
  - 0.2384
  - 0.8778
  - 0.7997
  frame: 11
  global_frame: 200
  prompt: the tiger is walking
- bbox_ratios:
  - 0.5042
  - 0.2394
  - 0.8825
  - 0.7996
  frame: 12
  global_frame: 201
  prompt: the tiger is walking
- bbox_ratios:
  - 0.5046
  - 0.2349
  - 0.8836
  - 0.7959
  frame: 13
  global_frame: 202
  prompt: the tiger is walking
- bbox_ratios:
  - 0.5053
  - 0.2329
  - 0.8904
  - 0.7941
  frame: 14
  global_frame: 203
  prompt: the tiger is walking
- bbox_ratios:
  - 0.5044
  - 0.2298
  - 0.9002
  - 0.7975
  frame: 15
  global_frame: 204
  prompt: the tiger is walking
- bbox_ratios:
  - 0.5102
  - 0.2259
  - 0.9034
  - 0.7962
  frame: 16
  global_frame: 205
  prompt: the tiger is walking
- bbox_ratios:
  - 0.5108
  - 0.2238
  - 0.9039
  - 0.7945
  frame: 17
  global_frame: 206
  prompt: the tiger is walking
- bbox_ratios:
  - 0.5063
  - 0.2235
  - 0.9081
  - 0.7887
  frame: 18
  global_frame: 207
  prompt: the tiger is walking
- bbox_ratios:
  - 0.5096
  - 0.2255
  - 0.9142
  - 0.7922
  frame: 19
  global_frame: 208
  prompt: the tiger is walking
- bbox_ratios:
  - 0.5126
  - 0.2242
  - 0.9206
  - 0.7882
  frame: 20
  global_frame: 209
  prompt: the tiger is walking
- bbox_ratios:
  - 0.5048
  - 0.2218
  - 0.9232
  - 0.7904
  frame: 21
  global_frame: 210
  prompt: the tiger is walking
- bbox_ratios:
  - 0.5114
  - 0.2173
  - 0.9428
  - 0.7852
  frame: 22
  global_frame: 211
  prompt: the tiger is walking
- bbox_ratios:
  - 0.5097
  - 0.2115
  - 0.9537
  - 0.7756
  frame: 23
  global_frame: 212
  prompt: the tiger is walking
motion_id: 29
motion_iter: 0
num_inference_steps: null
object_name: tiger
seed: 4
source_clip: QUURZXDO_98_249
token_inds:
- 2
trailblazer:
  num_dd_spatial_steps: 5
  num_dd_temporal_steps: 5
  spatial_strengthen_scale: 0.15
  spatial_weaken_scale: 0.001
  temp_strengthen_scale: 0.15
  temp_weaken_scale: 0.001
  trailing_length: 15
width: 320
