height: 320
keyframe:
- bbox_ratios:
  - 0.1942
  - 0.3115
  - 0.3651
  - 0.5595
  frame: 0
  global_frame: 256
  prompt: the goat is running
- bbox_ratios:
  - 0.1942
  - 0.3133
  - 0.3645
  - 0.5606
  frame: 1
  global_frame: 257
  prompt: the goat is running
- bbox_ratios:
  - 0.1941
  - 0.3151
  - 0.3639
  - 0.5617
  frame: 2
  global_frame: 258
  prompt: the goat is running
- bbox_ratios:
  - 0.194
  - 0.3168
  - 0.3633
  - 0.5629
  frame: 3
  global_frame: 259
  prompt: the goat is running
- bbox_ratios:
  - 0.1935
  - 0.3178
  - 0.3617
  - 0.5649
  frame: 4
  global_frame: 260
  prompt: the goat is running
- bbox_ratios:
  - 0.1932
  - 0.3194
  - 0.3622
  - 0.5648
  frame: 5
  global_frame: 261
  prompt: the goat is running
- bbox_ratios:
  - 0.1929
  - 0.3211
  - 0.3627
  - 0.5647
  frame: 6
  global_frame: 262
  prompt: the goat is running
- bbox_ratios:
  - 0.1926
  - 0.3227
  - 0.3632
  - 0.5646
  frame: 7
  global_frame: 263
  prompt: the goat is running
- bbox_ratios:
  - 0.1923
  - 0.3243
  - 0.3637
  - 0.5645
  frame: 8
  global_frame: 264
  prompt: the goat is running
- bbox_ratios:
  - 0.192
  - 0.3259
  - 0.3642
  - 0.5644
  frame: 9
  global_frame: 265
  prompt: the goat is running
- bbox_ratios:
  - 0.1918
  - 0.3276
  - 0.3647
  - 0.5643
  frame: 10
  global_frame: 266
  prompt: the goat is running
- bbox_ratios:
  - 0.1915
  - 0.3292
  - 0.3652
  - 0.5641
  frame: 11
  global_frame: 267
  prompt: the goat is running
- bbox_ratios:
  - 0.1915
  - 0.329
  - 0.3656
  - 0.5642
  frame: 12
  global_frame: 268
  prompt: the goat is running
- bbox_ratios:
  - 0.1919
  - 0.3297
  - 0.3672
  - 0.5653
  frame: 13
  global_frame: 269
  prompt: the goat is running
- bbox_ratios:
  - 0.1922
  - 0.3305
  - 0.3687
  - 0.5664
  frame: 14
  global_frame: 270
  prompt: the goat is running
- bbox_ratios:
  - 0.1926
  - 0.3312
  - 0.3703
  - 0.5675
  frame: 15
  global_frame: 271
  prompt: the goat is running
- bbox_ratios:
  - 0.1929
  - 0.332
  - 0.3719
  - 0.5686
  frame: 16
  global_frame: 272
  prompt: the goat is running
- bbox_ratios:
  - 0.1933
  - 0.3327
  - 0.3735
  - 0.5697
  frame: 17
  global_frame: 273
  prompt: the goat is running
- bbox_ratios:
  - 0.1936
  - 0.3334
  - 0.3751
  - 0.5708
  frame: 18
  global_frame: 274
  prompt: the goat is running
- bbox_ratios:
  - 0.194
  - 0.3342
  - 0.3767
  - 0.5719
  frame: 19
  global_frame: 275
  prompt: the goat is running
- bbox_ratios:
  - 0.1941
  - 0.3365
  - 0.3803
  - 0.5729
  frame: 20
  global_frame: 276
  prompt: the goat is running
- bbox_ratios:
  - 0.1926
  - 0.3397
  - 0.3888
  - 0.5761
  frame: 21
  global_frame: 277
  prompt: the goat is running
- bbox_ratios:
  - 0.1923
  - 0.3417
  - 0.3903
  - 0.5756
  frame: 22
  global_frame: 278
  prompt: the goat is running
- bbox_ratios:
  - 0.1909
  - 0.3427
  - 0.389
  - 0.5767
  frame: 23
  global_frame: 279
  prompt: the goat is running
motion_id: 31
motion_iter: 0
num_inference_steps: null
object_name: goat
seed: 4
source_clip: MHFAFKEW_225_343
token_inds:
- 2
trailblazer:
  num_dd_spatial_steps: 5
  num_dd_temporal_steps: 5
  spatial_strengthen_scale: 0.15
  spatial_weaken_scale: 0.001
  temp_strengthen_scale: 0.15
  temp_weaken_scale: 0.001
  trailing_length: 15
width: 320
